name: Bunny Userbot
on:
  workflow_dispatch: # Allows you to start it manually from the Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      # Frees up ~20GB of space for larger video handling
      - name: Maximize Runner Space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt
          
      - name: Run Bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: ${{ secrets.SESSION_STRING }}
          BUNNY_LIBRARY_ID: ${{ secrets.BUNNY_LIBRARY_ID }}
          BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
        run: python main.py
